import AppKit
import Foundation

struct ClipItem: Codable, Identifiable, Equatable {
    let id: UUID
    let text: String
    let date: Date
    let appName: String?
}

/// 剪贴板历史:轮询 changeCount 记录文本,跳过 transient/concealed(密码管理器)条目
@MainActor
final class ClipboardStore: ObservableObject {
    static let shared = ClipboardStore()

    @Published private(set) var items: [ClipItem] = []

    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount
    private var suppressUntil = Date.distantPast
    private let maxItems = 50
    private let maxTextLength = 50_000

    private static let skippedTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    private let fileURL: URL = {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        return base.appendingPathComponent("YiJian/clipboard.json")
    }()

    private init() {}

    func start() {
        load()
        lastChangeCount = NSPasteboard.general.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: 0.8, repeats: true) { _ in
            Task { @MainActor in ClipboardStore.shared.poll() }
        }
    }

    /// 自己要临时动剪贴板(取词兜底、替换回填)前调用,避免记进历史
    func suppress(for seconds: TimeInterval) {
        suppressUntil = Date().addingTimeInterval(seconds)
    }

    func remove(id: UUID) {
        items.removeAll { $0.id == id }
        save()
    }

    func clear() {
        items = []
        save()
    }

    // MARK: - 采集

    private func poll() {
        guard SettingsStore.clipboardHistoryEnabled else { return }
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount
        guard Date() >= suppressUntil else { return }

        let types = Set((pb.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.skippedTypes) else { return }
        guard let text = pb.string(forType: .string),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
              text.count <= maxTextLength else { return }

        add(text)
    }

    private func add(_ text: String) {
        let appName = NSWorkspace.shared.frontmostApplication?.localizedName
        if let existing = items.firstIndex(where: { $0.text == text }) {
            let old = items.remove(at: existing)
            items.insert(ClipItem(id: old.id, text: text, date: Date(), appName: old.appName ?? appName), at: 0)
        } else {
            items.insert(ClipItem(id: UUID(), text: text, date: Date(), appName: appName), at: 0)
        }
        if items.count > maxItems {
            items.removeLast(items.count - maxItems)
        }
        save()
    }

    // MARK: - 持久化

    private func load() {
        guard let data = try? Data(contentsOf: fileURL),
              let decoded = try? JSONDecoder().decode([ClipItem].self, from: data) else { return }
        items = decoded
    }

    private func save() {
        let snapshot = items
        Task.detached(priority: .utility) { [fileURL] in
            guard let data = try? JSONEncoder().encode(snapshot) else { return }
            try? FileManager.default.createDirectory(at: fileURL.deletingLastPathComponent(), withIntermediateDirectories: true)
            try? data.write(to: fileURL, options: .atomic)
        }
    }
}
